Repository VerifiedInc/one-click-demo-web, pull requests merged in 2024-06, with the labels that each got.

#65 feat: drag and drop
  app/components/DragIndicator.tsx
  app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/contexts/CredentialRequestFieldContext.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  package-lock.json
  package.json
  remix.config.js
Labels: 20 min review

#66 fix: add default values
  app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
Labels: 1 min review

#68 code block
  app/config.client.ts
  app/features/customConfig/components/CustomizableDialog/components/Body.tsx
  app/features/customConfig/components/CustomizableDialog/components/CodeBlock.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/share/hooks/useShareDemo.ts
  app/hooks/useCopyToClipboard.ts
  app/root.tsx
  app/utils/object.ts
  package-lock.json
  package.json
Labels: 30 min review

#70 feat: copy to clipboard when share api is not available for browser
  app/features/share/hooks/useShareDemo.ts
Labels: 1 min review

#71 small fixes
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/request/CredentialsDisplay/CredentialsDisplayContext.tsx
  app/features/request/DataField/DataFieldHeader/HeaderSelect/index.tsx
  app/features/request/request/RequestBody.tsx
  app/routes/account.tsx
  app/routes/personal-information.tsx
Labels: 1 min review

#72 fix: conditionally render extra component
  app/features/request/request/RequestBody.tsx
Labels: 1 min review, single-line

#73 [CI] sentry org name fix
  .circleci/config.yml
Labels: 1 min review, single-line

#74 chore: rename signin to login and add access title
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/types.ts
Labels: 1 min review
