Repository VerifiedInc/one-click-demo-web, pull requests merged in 2024-04, with the labels that each got.

#24 chore: remove book a call from layout
  app/Layout.tsx
Labels: hotfix, 1 min review, single-line

#26 [CI] latest orb for staging env
  .circleci/config.yml
Labels: hotfix, 1 min review

#28 fix: add correct regex pattern for full dob
  app/validations/birthDate.schema.ts
Labels: hotfix, 1 min review, single-line

#29 fix: attempt to fix redirect url
  app/routes/personal-information.tsx
Labels: 1 min review
