Repository VerifiedInc/one-click-demo-web, pull requests merged in 2024-02, with the labels that each got.

#1 feat: account page
  app/components/IconBoxAndLabel.tsx
  app/features/oneClick/useCases/getOneClickUseCase.ts
  app/libs/driver/index.ts
  app/libs/driver/style.css
  app/routes/account.tsx
  app/routes/index.tsx
  app/routes/personal-information.tsx
  app/routes/verified.tsx
  package-lock.json
  package.json
Labels: 5 min review

#2 feat: add socket.io event to 1-click success flow
  .env.example
  app/Layout.tsx
  app/context/SocketContext.tsx
  app/features/register/components/OneClickSMSDialogContent.tsx
  app/lib/socket-io.js
  app/root.tsx
  app/routes/register.tsx
  app/utils/socket.ts
  package-lock.json
  package.json
  server.js
Labels: 5 min review

#4 chore: allow verified inc and webflow subdomain framing ancestor
  server.js
Labels: 1 min review

#5 [CI] update to use new deployment name
  .circleci/config.yml
Labels: 1 min review, single-line

#6 chore: add calendly to book a call and dob input pattern changes
  .env.example
  app/Layout.tsx
  app/components/BookACallButton.tsx
  app/components/VerifiedIncLogo.tsx
  app/config.client.ts
  app/config.ts
  app/features/register/components/OneClickFormNonHosted.tsx
  app/features/register/components/OneClickPoweredBy.tsx
  app/root.tsx
  app/routes/personal-information.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/utils/date.ts
  app/validations/birthDate.schema.ts
  server.js
Labels: 5 min review

#7 chore: update the design webflow domain
  server.js
Labels: 1 min review, single-line

#8 fix: format conditionally dob
  app/routes/register.tsx
Labels: hotfix, 1 min review, single-line

#9 chore: add og, input hack to scroll to top and link powered by
  app/components/PhoneInput.tsx
  app/features/register/components/OneClickForm.tsx
  app/features/register/components/OneClickFormNonHosted.tsx
  app/features/register/components/OneClickPoweredBy.tsx
  app/hooks/useFullName.ts
  app/root.tsx
  app/routes/index.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/session.server.ts
Labels: 5 min review

#10 fix: enforce https protocol when redirecting to comply with Mixed Content error
  app/features/register/components/OneClickSMSDialogContent.tsx
Labels: hotfix

#11 chore: update og
  app/root.tsx
Labels: 1 min review, single-line
