Repository VerifiedInc/one-click-demo-web, pull requests merged in 2024-05, with the labels that each got.

#30 feat: custom dialog
  .env.example
  Dockerfile
  README.md
  app/Layout.tsx
  app/components/OriginalButton.tsx
  app/components/RequiredLabel.tsx
  app/components/Tip.tsx
  app/config.client.ts
  app/config.ts
  app/coreAPI.server.ts
  app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
  app/features/customConfig/components/CustomizableDialog/components/CustomizeStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldDeleteModal.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldDescription.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldMandatory.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldSection.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldUserInput.tsx
  app/features/customConfig/components/CustomizableDialog/components/DescriptionField.tsx
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/HostedField.tsx
  app/features/customConfig/components/CustomizableDialog/components/RadioOption.tsx
  app/features/customConfig/components/CustomizableDialog/components/RedirectUrlField.tsx
  app/features/customConfig/components/CustomizableDialog/components/SectionAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/components/CustomizableDialog/components/VerificationOptionsField.tsx
  app/features/customConfig/components/CustomizableDialog/contexts/CredentialRequestFieldContext.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/customConfig/components/CustomizableDialog/utils/buildDataFieldValue.ts
  app/features/customConfig/components/CustomizableDialog/utils/defaultValues.ts
  app/features/customConfig/contexts/CustomConfig.tsx
  app/features/customConfig/mappers/mapFormState.ts
  app/features/customConfig/types.ts
  app/features/customConfig/validators/form.ts
  app/features/environment/helpers/getAdminKey.ts
  app/features/environment/helpers/getBaseUrl.ts
  app/features/environment/helpers/ifEnv.ts
  app/features/environment/helpers/index.ts
  app/features/environment/helpers/isDummy.ts
  app/features/environment/helpers/isReal.ts
  app/features/oneClick/mappers/mapOneClickOptions.ts
  app/features/state/mappers/mapState.ts
  app/features/state/services/findState.ts
  app/features/state/types.ts
  app/hooks/useDebounce.ts
  app/routes/custom-demo-state.ts
  app/routes/register.tsx
  app/routes/schemas.ts
  app/styles/colors.ts
  app/styles/theme.ts
  app/utils/getBrandSet.ts
  app/utils/json.ts
  migrations/20230119210429_users.ts
  package-lock.json
  package.json
  prisma/migrations/0_init/migration.sql
  prisma/schema.prisma
  prisma/state.ts
  public/horizontal-green-logo.svg
Labels: 10 min review

#31 refactor: update docker command
  Dockerfile
Labels: 1 min review, single-line

#32 fix: brand favicon
  app/routes/favicon.tsx
Labels: 1 min review, single-line

#33 fix: display dialog when there are multi env parameter
  app/Layout.tsx
Labels: 1 min review, single-line

#34 fix: prisma generate on db migration
  package.json
Labels: 1 min review, single-line

#35 chore: generate client locally
  .eslintrc.js
  .gitignore
  .prettierignore
  .trunk/trunk.yaml
  prisma/schema.prisma
  prisma/state.ts
Labels: 1 min review

#38 refactor: generate prisma client docker
  Dockerfile
Labels: hotfix, 1 min review

#39 fix: add correct command
  Dockerfile
Labels: hotfix, 1 min review, single-line

#40 feat: update to generate Prisma client and run migrations in production
  Dockerfile
  README.md
  package.json
Labels: 1 min review

#41 fix: change the entrypoint
  Dockerfile
Labels: 1 min review, single-line

#42 fix: oneClick demo dialog and ApiKey
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/utils/getBrandSet.ts
Labels: 1 min review

#43 [State] set in redirectUrl.
  app/Layout.tsx
  app/coreAPI.server.ts
  app/features/oneClick/mappers/mapOneClickOptions.ts
  app/routes/favicon.tsx
  app/routes/register.tsx
  app/utils/getBrandSet.ts
Labels: 1 min review

#44 fix: pass prisma singleton through context
  app/coreAPI.server.ts
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/oneClick/useCases/getOneClickUseCase.ts
  app/features/state/services/findState.ts
  app/root.tsx
  app/routes/account.tsx
  app/routes/custom-demo-state.ts
  app/routes/favicon.tsx
  app/routes/index.tsx
  app/routes/personal-information.tsx
  app/routes/register.tsx
  app/routes/verified.tsx
  app/session.server.ts
  app/utils/getBrandSet.ts
  prisma/prisma.js
  prisma/state.ts
  server.js
Labels: 10 min review

#45 [Redirect] fixed and small logging improvement
  app/coreAPI.server.ts
  app/features/customConfig/components/CustomizableDialog/index.tsx
Labels: hotfix, 1 min review

#46 optOutfix
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/logout/usecases/logoutUseCase.ts
  app/features/oneClick/useCases/getOneClickUseCase.ts
  app/routes/register.tsx
  server.js
Labels: 1 min review

#47 fix: get 1click result using brands from config state and favicon
  README.md
  app/coreAPI.server.ts
  app/features/oneClick/useCases/getOneClickUseCase.ts
  app/root.tsx
  app/routes/register.tsx
  app/session.server.ts
  app/utils/getBrandSet.ts
Labels: 5 min review

#48 chore: add customize button and tooltip for mobile
  app/Layout.tsx
  app/components/Tip.tsx
  app/features/customConfig/components/CustomizeButton.tsx
Labels: 1 min review

#50 fix default values non hosted
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
  app/features/customConfig/components/CustomizableDialog/components/DescriptionField.tsx
  app/features/customConfig/components/CustomizableDialog/components/HostedField.tsx
  app/features/customConfig/components/CustomizableDialog/components/RedirectUrlField.tsx
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/personalInformation/hooks/usePersonalInformationFields.ts
  app/features/personalInformation/types.ts
Labels: 5 min review

#51 fix ui texts
  app/Layout.tsx
  app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/HostedField.tsx
  app/features/customConfig/components/CustomizableDialog/components/RadioOption.tsx
  app/features/customConfig/components/CustomizableDialog/components/SectionAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/components/CustomizableDialog/components/VerificationOptionsField.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/state/types.ts
  app/routes/custom-demo-state.ts
  app/styles/theme.ts
  app/styles/verified-colors.ts
  app/styles/verified-theme.ts
  app/utils/credential.ts
  app/utils/getBrandSet.ts
  prisma/migrations/20240517203506_update_brands_column_name/migration.sql
  prisma/migrations/20240517211406_drop_old_columns/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/state.ts
Labels: 30 min review

#53 fix: non-hosted redirect url to use use the presentationRequests
  app/routes/personal-information.tsx
Labels: 1 min review, single-line

#54 fix: redirect non-hosted cta to redirect to verified page
  app/routes/personal-information.tsx
Labels: hotfix, 1 min review, single-line

#55 fix: display ssn term
  app/utils/credential.ts
Labels: 1 min review, single-line

#56 fix: form validity, add mock term, add disabled accordion state
  app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
  app/features/customConfig/components/CustomizableDialog/components/DescriptionField.tsx
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/RedirectUrlField.tsx
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/components/CustomizableDialog/index.tsx
  app/features/customConfig/validators/form.ts
  app/styles/verified-theme.ts
  app/validations/birthDate.schema.ts
Labels: hotfix, 1 min review

#57 fix: remove is valid
  app/features/customConfig/components/CustomizableDialog/components/CustomizeStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
Labels: 1 min review

#58 fix: rename value
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
Labels: hotfix, 1 min review, single-line

#59 chore: add test id
  app/components/OTPInput.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldDeleteModal.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldDescription.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldMandatory.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldSection.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldUserInput.tsx
  app/features/customConfig/components/CustomizableDialog/components/DescriptionField.tsx
  app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx
  app/features/customConfig/components/CustomizableDialog/components/HostedField.tsx
  app/features/customConfig/components/CustomizableDialog/components/RedirectUrlField.tsx
  app/features/customConfig/components/CustomizableDialog/components/SectionAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/TitleField.tsx
  app/features/customConfig/components/CustomizableDialog/components/VerificationOptionsField.tsx
Labels: hotfix, 5 min review

#60 fix: pass params input props
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
Labels: 1 min review, single-line

#61 chore: changed Verified Inc to Verified
  README.md
  app/coreAPI.server.ts
  app/features/customConfig/components/CustomizableDialog/components/HostedField.tsx
  app/features/register/components/OneClickLegalText.tsx
  app/features/register/components/OneClickPoweredBy.tsx
  app/routes/favicon.tsx
  public/1-click-powered-by.svg
  public/horizontal-green-logo.svg
Labels: 1 min review

#62 refactor: update styles from the delete buttons dialog
  app/features/customConfig/components/CustomizableDialog/components/DataFieldDeleteModal.tsx
Labels: 1 min review, single-line

#63 update ux data field section
  app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
  app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx
Labels: hotfix, 1 min review

#64 fix: change mask pattern
  app/features/personalInformation/hooks/usePersonalInformationFields.ts
Labels: 1 min review, single-line
